### PR TITLE
Removing Warning when updating content URL and the disqus API returns false.

### PR DESCRIPTION
**Pull request by simonbbrown**
adding check on response to account for negative responses, removes warning when running in debug mode and changing a URL

### CODE REVIEW

**Comment by mattrobenolt** [comment]
In what case is `$response` empty?

**Comment by simonbbrown** [comment]
Response came back as false when I was updating a url on a custom post type.

I was working on a local environment which is cloned from a UAT environment
- I'm not sure about the config for disqus as I don't have access to the
account at the moment, but suspect that there might of been some
discrepancies with the url from the URL's between local/UAT and hence the
false response from the API.

**Comment by mattrobenolt** [comment]
wfm, thanks! :cake:

**Comment by simonbbrown** [comment]
Not a problem at all - Thanks for merging!

**Pull request merged**
