### PR TITLE
Schedule dsq_sync_forum hourly at most.

### PR DESCRIPTION
**Pull request by boltronics**
For:
```
> SELECT * FROM wp_options WHERE option_name = 'cron';
```

Turn this:
```
option_value: a:30611:{i:1438950335;a:1:{s:14:"dsq_sync_forum";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:2:{s:8:"schedule";b:0;s:4:"args";a:0:{}}}}i:1438950336;a:1:{s:14:"dsq_sync_forum";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:2:{s:8:"schedule";b:0;s:4:"args";a:0:{}}}}i:1438950338;a:1:{s:14:"dsq_sync_forum";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:2:{s:8:"schedule";b:0;s:4:"args";a:0:{}}}}i:1438950341;a:1:{s:14:"dsq_sync_forum";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:2:{s:8:"schedule";b:0;s:4:"args";a:0:{}}}}i:1438950342;a:1:{s:14:"dsq_sync_forum";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:2:{s:8:"schedule";b:0;s:4:"args";a:0:{}}}}i:1438950344;a:1:{s:14:"dsq_sync_forum";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:2:{s:8:"schedule";b:0;s:4:"args";a:0:{}}}}i:1438950345;a:1:{s:14:"dsq_sync_forum";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:2:{s:8:"schedule";b:0;s:4:"args";a:0:{}}}}i:1438950347;a:1:{s:14:"dsq_sync_forum";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:2:{s:8:"schedule";b:0;s:4:"args";a:0:{}}}}i:1438950348;a:1:{s:14:"dsq_sync_forum";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:2:{s:8:"schedule";b:0;s:4:"args";a:0:{}}}}i:1438950350;a:1:{s:14:"dsq_sync_forum";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:2:{s:8:"schedule";b:0;s:4:"args";a:0:{}}}}i:1438950352;a:1:{s:14:"dsq_sync_forum";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:2:{s:8:"schedule";b:0;s:4:"args";...
```

into this:
```
option_value: a:4:{i:1438937105;a:4:{s:48:"check_plugin_updates-organize-series-cpt-support";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:12:"every12hours";s:4:"args";a:0:{}s:8:"interval";i:43200;}}s:16:"wp_version_check";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}s:17:"wp_update_plugins";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}s:16:"wp_update_themes";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}}i:1438937412;a:1:{s:14:"dsq_sync_forum";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:6:"hourly";s:4:"args";a:0:{}s:8:"interval";i:3600;}}}i:1439000520;a:1:{s:20:"wp_maybe_auto_update";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}}s:7:"version";i:2;}
```

Now my servers can stop exploding. :)

### CODE REVIEW

**Comment by tail** [comment]
Thanks for the pull.  I'm +1 on adding the check to call `wp_next_scheduled` before scheduling, but I'd rather not have every site syncing hourly when nothing has happened on a site.  If you can just leave the old behavior but keep the new check, I'd happily merge this.

**Comment by archon810** [comment]
Hi guys,

I run AndroidPolice.com and APKMirror.com, and several times so far in the past several years, we've had really awful issues, which I inevitably eventually pin down to dsq_sync_forum.

Just now it happened again, and I found this: https://gist.github.com/archon810/502d43fadb2afc085bd8d8ab0866a8db. 7500 dsq_sync_forums.

Each process seems to not only load about 1MB of cron data into memory, but it also writes it back, even if it has nothing to do with cron, seemingly. So without stopping all the web servers from writing into mysql, it's impossible to wipe the cron entry to delete these dsq_sync_forums.

Since I'm already familiar with the issue, I was able to prevent it from blowing up our site for too long just now, but take a read here about what happened last time: https://core.trac.wordpress.org/ticket/15148#comment:9.

I'd actually blame WP for devising such a devious and terrible cron system all stored in a single field, but at the same time, Disqus shouldn't be creating duplicate dsq_sync_forum until your site explodes.

Can we talk about resolving it?

More around the web:
https://wordpress.org/support/topic/high-server-load-and-dsq_sync_forum-problem
https://disqus.com/home/channel/discussdisqus/discussion/channel-discussdisqus/tons_of_dsq_sync_forum_entries_in_cron_row_wp_options_and_10x_server_loads/
Etc.

**Comment by archon810** [comment]
I filed a proper ticket for this issue here https://github.com/disqus/disqus-wordpress/issues/113.

I think you're on the right track, except you need to create a custom 5-minutely schedule like so https://codex.wordpress.org/Plugin_API/Filter_Reference/cron_schedules, in order for the functionality to remain similar to the intended one (which is to sync at least every 5 min).

**Comment by archon810** [comment]
Here's my fix: #114. I've tested it on our busy server, and it seems to have worked perfectly.

**Comment by tail** [comment]
Superseded by #114.

**Pull request closed without merging**
